ALTER TABLE users
    ADD COLUMN email VARCHAR(200) NOT NULL UNIQUE,
    ADD COLUMN is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    ALTER COLUMN username TYPE VARCHAR(70),
    ALTER COLUMN username SET NOT NULL;
